# Generated by Django 5.0 on 2023-12-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('national_id', models.CharField(default=None, max_length=10)),
                ('phone_number', models.CharField(default=None, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hired_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('national_id', models.CharField(default=None, max_length=10)),
                ('phone_number', models.CharField(default=None, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('register_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
