# Generated by Django 5.0 on 2023-12-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='national_id',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
    ]
